#!/usr/bin/env python3
"""Generate docs/example-plate.svg — the drawing the plugin ships with.

Original artwork, generated rather than drawn, so nothing in this repo depends
on somebody else's file. It exists because a plugin whose whole argument is
"point it at your vector artwork" has to have something to argue with on first
run, and because every screenshot, the demo video and the web demo should all
be showing the same thing.

## What it is designed to exercise

An astrolabe plate: concentric rings, a degree scale, radial spokes, and a
cluster of fine detail near the centre. Every part of that is chosen for
something the plugin does.

- **Fine detail that a bitmap loses.** The innermost tick marks are a fraction
  of a unit wide. At 1:1 on a 1080 frame they are sub-pixel; zoomed eight times
  they are the thing that shows the re-rasterisation working, because a
  pre-rendered PNG of this file simply does not contain them.

- **Wildly different path lengths.** A 360-degree ring and a two-unit tick
  differ by three orders of magnitude, which is what makes Longest First and
  Shortest First visibly different orders rather than two shufflings of the
  same thing.

- **Fills and strokes on separate shapes.** The rings and ticks are stroke with
  no fill; the cardinal markers and the centre boss are fill with no stroke.
  Draw: Stroke Only and Draw: Fill Only therefore produce two genuinely
  different pictures rather than one picture and a slightly thinner version of
  it.

- **A few hundred shapes.** Enough that Stagger has somewhere to go and that
  the cost measured by `burintest --cost` is representative of a real drawing,
  rather than of a test case with four rectangles in it.

Deliberately no text: nanosvg ignores `<text>` entirely, so a drawing shipped
as the example must not contain any — the file that demonstrates the plugin
cannot also be the file that demonstrates its main limitation.

    python3 tools/make_example_svg.py
"""

import math
import os

SIZE = 1000.0
CX = CY = SIZE / 2.0

INK = "#1b1b1f"
ACCENT = "#c8452e"
COOL = "#2e6ec8"


def polar(radius, degrees):
    a = math.radians(degrees - 90.0)
    return CX + radius * math.cos(a), CY + radius * math.sin(a)


def fmt(v):
    """Trim trailing zeros. A 400-shape file written at full float precision is
    three times the size for no visible difference."""
    return f"{v:.3f}".rstrip("0").rstrip(".")


def main():
    out = []
    add = out.append

    add(f'<svg xmlns="http://www.w3.org/2000/svg" width="{fmt(SIZE)}" '
        f'height="{fmt(SIZE)}" viewBox="0 0 {fmt(SIZE)} {fmt(SIZE)}">')
    add('  <!-- Generated by tools/make_example_svg.py. Original work, MIT, '
        'part of stoatworks-labs/burin. -->')

    # --- the rings ------------------------------------------------------
    # Widest first so the document order is also roughly the drawing order,
    # which is what makes Reveal: Document read as somebody constructing it.
    for radius, width in ((470, 2.5), (455, 1.0), (392, 1.6), (300, 1.0),
                          (232, 1.6), (150, 1.0), (96, 1.2)):
        add(f'  <circle cx="{fmt(CX)}" cy="{fmt(CY)}" r="{fmt(radius)}" '
            f'fill="none" stroke="{INK}" stroke-width="{fmt(width)}"/>')

    # --- the degree scale ------------------------------------------------
    # 360 ticks, every fifth longer, every thirtieth longer again and in the
    # accent colour. This is most of the shape count and all of the fine detail.
    for deg in range(360):
        if deg % 30 == 0:
            inner, width, colour = 392.0, 1.8, ACCENT
        elif deg % 5 == 0:
            inner, width, colour = 428.0, 1.1, INK
        else:
            inner, width, colour = 444.0, 0.55, INK

        x1, y1 = polar(inner, deg)
        x2, y2 = polar(455.0, deg)
        add(f'  <path d="M {fmt(x1)} {fmt(y1)} L {fmt(x2)} {fmt(y2)}" '
            f'fill="none" stroke="{colour}" stroke-width="{fmt(width)}"/>')

    # --- radial spokes ---------------------------------------------------
    for deg in range(0, 360, 15):
        x1, y1 = polar(96.0, deg)
        x2, y2 = polar(392.0, deg)
        add(f'  <path d="M {fmt(x1)} {fmt(y1)} L {fmt(x2)} {fmt(y2)}" '
            f'fill="none" stroke="{INK}" stroke-width="0.7"/>')

    # --- the almucantar arcs ---------------------------------------------
    # Off-centre circles clipped by nothing, which is what an astrolabe plate
    # actually looks like and which gives the reveal some long curves to run
    # along that are not concentric with everything else.
    for i in range(1, 8):
        r = 40.0 + i * 34.0
        oy = CY - i * 16.0
        add(f'  <circle cx="{fmt(CX)}" cy="{fmt(oy)}" r="{fmt(r)}" '
            f'fill="none" stroke="{COOL}" stroke-width="0.8"/>')

    # --- cardinal markers: FILL, no stroke -------------------------------
    # So that Draw: Fill Only leaves four marks and a boss, and Draw: Stroke
    # Only leaves everything except them. Two different pictures.
    for deg in (0, 90, 180, 270):
        tipx, tipy = polar(415.0, deg)
        lx, ly = polar(392.0, deg - 2.2)
        rx, ry = polar(392.0, deg + 2.2)
        add(f'  <path d="M {fmt(tipx)} {fmt(tipy)} L {fmt(lx)} {fmt(ly)} '
            f'L {fmt(rx)} {fmt(ry)} Z" fill="{ACCENT}"/>')

    # --- the rete: a rotating star map, as filled points -----------------
    stars = [(58, 12), (121, 47), (196, 88), (243, 31), (298, 66),
             (334, 105), (17, 140), (79, 176), (152, 205), (211, 152),
             (265, 190), (312, 231), (41, 259), (108, 288), (175, 244),
             (228, 300), (283, 337), (349, 271), (95, 351), (161, 322)]
    for deg, radius in stars:
        x, y = polar(float(radius), float(deg))
        add(f'  <circle cx="{fmt(x)}" cy="{fmt(y)}" r="3.2" fill="{COOL}"/>')

    # --- the centre: the finest detail in the file -----------------------
    # A 40-tick scale inside a 96-unit radius. At 1:1 on a 1080 frame these are
    # under a pixel apart; they are the reason to zoom in.
    for i in range(40):
        deg = i * 9.0
        x1, y1 = polar(74.0, deg)
        x2, y2 = polar(96.0 if i % 5 else 60.0, deg)
        add(f'  <path d="M {fmt(x1)} {fmt(y1)} L {fmt(x2)} {fmt(y2)}" '
            f'fill="none" stroke="{INK}" stroke-width="0.4"/>')

    add(f'  <circle cx="{fmt(CX)}" cy="{fmt(CY)}" r="14" fill="{INK}"/>')
    add(f'  <circle cx="{fmt(CX)}" cy="{fmt(CY)}" r="5" fill="#ffffff"/>')

    add('</svg>')

    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    path = os.path.join(here, "docs", "example-plate.svg")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")

    shapes = sum(1 for line in out if line.lstrip().startswith(("<circle", "<path")))
    print(f"{path}: {shapes} shapes, {os.path.getsize(path)} bytes")


if __name__ == "__main__":
    main()
